# Generated by Django 4.2.4 on 2023-08-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='توضیحات')),
                ('priority', models.BooleanField(verbose_name='اولویت')),
                ('is_done', models.BooleanField(verbose_name='تمام شده / نشده')),
            ],
            options={
                'db_table': 'Todos_List',
            },
        ),
    ]
